//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleKhachHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Uid { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<short> PipelineId { get; set; }
    }
}
